repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/christopher-hacker/enforce-notebook-run-order
    rev: 0.1.4
    hooks:
      - id: enforce-notebook-run-order
        name: enforce-notebook-run-order
        entry: enforce-notebook-run-order
        types: [jupyter]
